import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import {
  mkdir,
  mkdtemp,
  readFile,
  rename,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import process from "node:process";
import { describe, it } from "node:test";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import snapshot from "./fixtures/nursery-rhyme-runtime-snapshot.json" with { type: "json" };
import {
  compileNurseryRhymePackages,
  serializeGeneratedCatalog,
} from "../scripts/nursery-rhyme/compiler.mjs";
import { runRhymeCatalogGenerator } from "../scripts/generate-rhyme-catalog.mjs";
import { GENERATED_DUB_DEFINITIONS } from "../src/dubbing/generated-rhyme-catalog.ts";

const execFileAsync = promisify(execFile);
const repositoryRoot = fileURLToPath(new URL("..", import.meta.url));
const EMPTY_GENERATED =
  "// Generated by scripts/generate-rhyme-catalog.mjs. Do not edit.\n"
  + "export const GENERATED_DUB_DEFINITIONS = [] as const;\n";

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function scoreXml(lines) {
  const lineSource = lines.map((line) => [
    `<bookmark id="${line.id}"/>`,
    "<note><pitch><step>C</step><octave>4</octave></pitch>",
    `<duration>${line.duration ?? 1}</duration>`,
    "<lyric number=\"1\"><syllabic>single</syllabic>",
    `<text>${escapeXml(line.text)}</text><end-line/></lyric></note>`,
  ].join("")).join("");
  return [
    '<score-partwise version="4.0">',
    '<part-list><score-part id="P1"><part-name>Melody</part-name></score-part></part-list>',
    '<part id="P1"><measure number="1">',
    '<attributes><divisions>1</divisions></attributes>',
    '<direction><direction-type><metronome><beat-unit>quarter</beat-unit>',
    '<per-minute>60</per-minute></metronome></direction-type></direction>',
    '<note><rest/><duration>2</duration></note>',
    lineSource,
    "</measure></part></score-partwise>",
  ].join("");
}

function artwork(label) {
  return {
    alt: `${label} artwork`,
    height: 90,
    src: `https://media.parrotbook.com/nursery/v1/${label}.webp`,
    width: 160,
  };
}

function manifestLine(line) {
  const value = { ...line };
  delete value.duration;
  return value;
}

function manifestFor({
  id,
  lines,
  order,
  scenes,
  scoreSrc = "score.musicxml",
  slug,
  title = `${slug} title`,
} = {}) {
  const authoredScenes = scenes ?? [{
    artwork: artwork(`${slug}-scene-1`),
    id: "scene-1",
    lines,
    title: `${slug} scene`,
  }];
  const packageScenes = authoredScenes.map((scene) => ({
    ...scene,
    lines: scene.lines.map(manifestLine),
  }));
  return {
    countInBeats: 2,
    countInMidi: 72,
    id: id ?? `${slug}-v1`,
    order,
    scenes: packageScenes,
    schemaVersion: 1,
    score: {
      melodyPart: "P1",
      playbackParts: ["P1"],
      src: scoreSrc,
      volume: 0.5,
    },
    slug,
    title,
  };
}

function lineFor(slug, index = 1, overrides = {}) {
  return {
    guide: `guides/${slug}-guide-${index}.mp3`,
    id: `${slug}-v1-line-${index}`,
    text: index === 1 ? "Alpha" : "Beta",
    ...overrides,
  };
}

async function temporaryDirectory(t, prefix = "parrot-rhyme-compiler-") {
  const root = await mkdtemp(path.join(tmpdir(), prefix));
  t.after(() => rm(root, { force: true, recursive: true }));
  return root;
}

async function writeLedger(ledgerPath, rhymes = []) {
  await mkdir(path.dirname(ledgerPath), { recursive: true });
  await writeFile(
    ledgerPath,
    `${JSON.stringify({ schemaVersion: 1, rhymes }, null, 2)}\n`,
  );
}

async function compilerFixture(t, rhymes = []) {
  const root = await temporaryDirectory(t);
  const contentRoot = path.join(root, "content");
  const ledgerPath = path.join(root, "deployed.json");
  await mkdir(contentRoot, { recursive: true });
  await writeLedger(ledgerPath, rhymes);
  return { contentRoot, ledgerPath, root };
}

async function generatorFixture(t, rhymes = []) {
  const rootDir = await temporaryDirectory(t, "parrot-rhyme-generator-");
  const contentRoot = path.join(rootDir, "public", "assets", "nursery-rhymes");
  const ledgerPath = path.join(rootDir, "scripts", "nursery-rhyme-deployed-ids.json");
  const outputPath = path.join(rootDir, "src", "dubbing", "generated-rhyme-catalog.ts");
  await mkdir(contentRoot, { recursive: true });
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeLedger(ledgerPath, rhymes);
  await writeFile(outputPath, EMPTY_GENERATED);
  return { contentRoot, ledgerPath, outputPath, rootDir };
}

async function writePackage(contentRoot, {
  directory = undefined,
  id,
  lines,
  order = 1,
  scenes,
  scoreSrc,
  slug = "alpha",
  title,
} = {}) {
  const packageDir = path.join(contentRoot, directory ?? slug);
  const manifestLines = scenes?.flatMap((scene) => scene.lines)
    ?? lines
    ?? [lineFor(slug)];
  const manifest = manifestFor({
    id,
    lines: manifestLines,
    order,
    scenes,
    scoreSrc,
    slug,
    title,
  });
  await mkdir(packageDir, { recursive: true });
  await writeFile(
    path.join(packageDir, "rhyme.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
  );
  const scorePath = path.join(packageDir, manifest.score.src);
  await mkdir(path.dirname(scorePath), { recursive: true });
  await writeFile(scorePath, scoreXml(manifestLines));
  for (const guide of new Set(manifestLines.map((line) => line.guide))) {
    const guidePath = path.join(packageDir, ...guide.split("/"));
    await mkdir(path.dirname(guidePath), { recursive: true });
    await writeFile(guidePath, "guide bytes");
  }
  return { manifest, packageDir };
}

function fakeAudioRunner(calls = []) {
  return async (file, args, options) => {
    calls.push({ args, file, options });
    if (file === "ffprobe") {
      return { stdout: JSON.stringify({ format: { duration: "0.75" } }) };
    }
    return { stdout: Buffer.alloc(4) };
  };
}

function pcmWithPeak(sampleIndex) {
  const output = Buffer.alloc((sampleIndex + 1) * 4);
  output.writeFloatLE(1, sampleIndex * 4);
  return output;
}

function timelineAudioRunner(calls = []) {
  return async (file, args, options) => {
    calls.push({ args, file, options });
    if (file === "ffprobe") {
      return { stdout: JSON.stringify({ format: { duration: "0.75" } }) };
    }
    const timelineSeconds = args[args.indexOf("-t") + 1];
    return { stdout: pcmWithPeak(timelineSeconds === "1" ? 0 : 1_000) };
  };
}

function sortScoreEvents(events) {
  return events.sort((left, right) =>
    left.atMs - right.atMs
    || left.role.localeCompare(right.role)
    || left.midi - right.midi
    || left.durationMs - right.durationMs);
}

function normalizedGeneratedScore(definition) {
  const firstCueMs = definition.lines[0].cueMs;
  return sortScoreEvents([
    ...definition.lines.flatMap((line, lineIndex) =>
      definition.music.linePhrases[lineIndex].playbackNotes.map((note) => ({
        ...note,
        atMs: line.cueMs - firstCueMs + note.atMs,
      }))),
    ...definition.music.outroNotes.map((note) => ({
      ...note,
      atMs: note.atMs - firstCueMs,
    })),
  ]);
}

function expandedLegacyPhraseDurations(definition) {
  if (definition.phraseDurationsMs.length === definition.lines.length) {
    return definition.phraseDurationsMs;
  }
  return definition.lines.map(
    (_, index) => definition.phraseDurationsMs[index % definition.linesPerScene],
  );
}

function generatedCatalogContract(definitions) {
  return definitions.map((definition) => ({
    id: definition.id,
    route: definition.route,
    title: definition.title,
    countInMidi: definition.countInMidi,
    musicVolume: definition.music.volume,
    phraseDurationsMs: definition.music.linePhrases.map(({ durationMs }) => durationMs),
    linesPerScene: definition.linesPerScene,
    sceneTitles: definition.sceneTitles,
    sceneArtwork: definition.sceneArtwork,
    lineArtwork: definition.lineArtwork,
    lines: definition.lines.map(({ id, text }) => ({ id, text })),
    relativeCuesMs: definition.lines.map(({ cueMs }) => cueMs - definition.lines[0].cueMs),
    durationAfterLeadInMs: definition.durationMs - definition.lines[0].cueMs,
    normalizedScore: normalizedGeneratedScore(definition),
  }));
}

describe("nursery rhyme package discovery and compilation", () => {
  it("discovers packages deterministically by global order, independent of creation order", async (t) => {
    const first = await compilerFixture(t);
    const second = await compilerFixture(t);
    await writePackage(first.contentRoot, { directory: "z-package", order: 2, slug: "zebra" });
    await writePackage(first.contentRoot, { directory: "a-package", order: 1, slug: "apple" });
    await writePackage(second.contentRoot, { directory: "a-package", order: 1, slug: "apple" });
    await writePackage(second.contentRoot, { directory: "z-package", order: 2, slug: "zebra" });

    const firstCatalog = await compileNurseryRhymePackages({
      ...first,
      runTool: fakeAudioRunner(),
    });
    const secondCatalog = await compileNurseryRhymePackages({
      ...second,
      runTool: fakeAudioRunner(),
    });

    assert.deepEqual(firstCatalog.map(({ id }) => id), ["apple-v1", "zebra-v1"]);
    assert.equal(
      serializeGeneratedCatalog(firstCatalog),
      serializeGeneratedCatalog(secondCatalog),
    );
  });

  it("emits the complete flattened runtime shape and deduplicated guide records", async (t) => {
    const fixture = await compilerFixture(t);
    await writePackage(fixture.contentRoot, { slug: "alpha", title: "Alpha Song" });

    const catalog = await compileNurseryRhymePackages({
      ...fixture,
      runTool: fakeAudioRunner(),
    });

    assert.deepEqual(catalog, [{
      id: "alpha-v1",
      route: "/dubs/alpha",
      title: "Alpha Song",
      durationMs: 3_000,
      finalCueTailMs: 1_000,
      linesPerScene: 1,
      countInBeats: 2,
      countInMidi: 72,
      sceneTitles: ["alpha scene"],
      sceneArtwork: [artwork("alpha-scene-1")],
      lineArtwork: null,
      lines: [{
        id: "alpha-v1-line-1",
        text: "Alpha",
        cueMs: 2_000,
        durationMs: 1_000,
        guideAudioId: "alpha-guide-1",
        guideAudioSrc: "/assets/nursery-rhymes/alpha/guides/alpha-guide-1.mp3",
        guidePeakBars: Array(32).fill(0),
        words: [{ atMs: 0, durationMs: 1_000, endOffset: 5, startOffset: 0 }],
      }],
      music: {
        countInBeatMs: 1_000,
        countInDurationMs: 2_000,
        linePhrases: [{
          durationMs: 1_000,
          notes: [{ atMs: 0, durationMs: 1_000, midi: 60 }],
          playbackNotes: [{
            atMs: 0,
            durationMs: 1_000,
            midi: 60,
            role: "melody",
          }],
        }],
        outroNotes: [],
        volume: 0.5,
      },
      guides: [{
        id: "alpha-guide-1",
        src: "/assets/nursery-rhymes/alpha/guides/alpha-guide-1.mp3",
        text: "Alpha",
        durationMs: 750,
      }],
    }]);
  });

  it("inspects each unique guide-path and line-duration pair once", async (t) => {
    const fixture = await compilerFixture(t);
    const sharedGuide = "guides/shared.mp3";
    await writePackage(fixture.contentRoot, {
      lines: [
        lineFor("alpha", 1, { guide: sharedGuide, text: "Alpha" }),
        lineFor("alpha", 2, { duration: 2, guide: sharedGuide, text: "Alpha" }),
        lineFor("alpha", 3, { guide: sharedGuide, text: "Alpha" }),
      ],
      slug: "alpha",
    });
    const calls = [];

    const [definition] = await compileNurseryRhymePackages({
      ...fixture,
      runTool: timelineAudioRunner(calls),
    });

    assert.equal(calls.length, 4);
    assert.equal(definition.guides.length, 1);
    assert.deepEqual(
      definition.lines.map(({ durationMs }) => durationMs),
      [1_000, 2_000, 1_000],
    );
    const oneSecondBars = [1, ...Array(31).fill(0)];
    const twoSecondBars = [0, 1, ...Array(30).fill(0)];
    assert.deepEqual(
      definition.lines.map(({ guidePeakBars }) => guidePeakBars),
      [oneSecondBars, twoSecondBars, oneSecondBars],
    );
  });

  it("rejects duplicate global order, rhyme ID, slug/route, and guide stem", async (t) => {
    for (const duplicate of ["order", "id", "slug", "guide stem"]) {
      const fixture = await compilerFixture(t);
      const first = {
        directory: `${duplicate.replaceAll(" ", "-")}-a`,
        id: "first-v1",
        lines: [lineFor("first", 1, { guide: "guides/first-guide.mp3" })],
        order: 1,
        slug: "first",
      };
      const second = {
        directory: `${duplicate.replaceAll(" ", "-")}-b`,
        id: "second-v1",
        lines: [lineFor("second", 1, { guide: "guides/second-guide.mp3" })],
        order: 2,
        slug: "second",
      };
      if (duplicate === "order") second.order = first.order;
      if (duplicate === "id") second.id = first.id;
      if (duplicate === "slug") second.slug = first.slug;
      if (duplicate === "guide stem") {
        first.lines[0].guide = "guides/shared.mp3";
        second.lines[0].guide = "guides/shared.mp3";
      }
      await writePackage(fixture.contentRoot, first);
      await writePackage(fixture.contentRoot, second);

      await assert.rejects(
        compileNurseryRhymePackages({ ...fixture, runTool: fakeAudioRunner() }),
        new RegExp(`duplicate.*${duplicate === "slug" ? "slug|route" : duplicate}`, "i"),
      );
    }
  });

  it("uses rhyme-local scene and line uniqueness scopes", async (t) => {
    const valid = await compilerFixture(t);
    await writePackage(valid.contentRoot, { order: 1, slug: "alpha" });
    await writePackage(valid.contentRoot, { order: 2, slug: "beta" });
    await assert.doesNotReject(
      compileNurseryRhymePackages({ ...valid, runTool: fakeAudioRunner() }),
    );

    for (const duplicate of ["scene", "line"]) {
      const fixture = await compilerFixture(t);
      const firstLine = lineFor("alpha", 1);
      const secondLine = lineFor("alpha", 2, {
        id: duplicate === "line" ? firstLine.id : "alpha-v1-line-2",
      });
      await writePackage(fixture.contentRoot, {
        scenes: [
          { artwork: artwork("one"), id: "scene-1", lines: [firstLine], title: "One" },
          {
            artwork: artwork("two"),
            id: duplicate === "scene" ? "scene-1" : "scene-2",
            lines: [secondLine],
            title: "Two",
          },
        ],
        slug: "alpha",
      });
      await assert.rejects(
        compileNurseryRhymePackages({ ...fixture, runTool: fakeAudioRunner() }),
        new RegExp(`duplicate ${duplicate} id`, "i"),
      );
    }
  });

  it("rejects reuse of one normalized guide path for different exact text", async (t) => {
    const fixture = await compilerFixture(t);
    await writePackage(fixture.contentRoot, {
      lines: [
        lineFor("alpha", 1, { guide: "guides/shared.mp3", text: "Alpha" }),
        lineFor("alpha", 2, { guide: "guides/shared.mp3", text: "Beta" }),
      ],
      slug: "alpha",
    });

    await assert.rejects(
      compileNurseryRhymePackages({ ...fixture, runTool: fakeAudioRunner() }),
      /guide.*different.*text|different.*text.*guide/i,
    );
  });

  it("discovers a seventh package without a registration edit", async (t) => {
    const fixture = await compilerFixture(t);
    for (let index = 1; index <= 7; index += 1) {
      await writePackage(fixture.contentRoot, {
        order: index,
        slug: `rhyme-${index}`,
      });
    }

    const catalog = await compileNurseryRhymePackages({
      ...fixture,
      runTool: fakeAudioRunner(),
    });
    assert.equal(catalog.length, 7);
    assert.equal(catalog.at(-1).id, "rhyme-7-v1");
  });

  it("rejects missing manifests, scores, and guides with actionable paths", async (t) => {
    for (const missing of ["manifest", "score", "guide"]) {
      const fixture = await compilerFixture(t);
      const { manifest, packageDir } = await writePackage(fixture.contentRoot, {
        slug: missing,
      });
      const missingPath = missing === "manifest"
        ? path.join(packageDir, "rhyme.json")
        : missing === "score"
          ? path.join(packageDir, manifest.score.src)
          : path.join(packageDir, ...manifest.scenes[0].lines[0].guide.split("/"));
      await rm(missingPath);

      await assert.rejects(
        compileNurseryRhymePackages({ ...fixture, runTool: fakeAudioRunner() }),
        new RegExp(`${missing}.*missing|${path.basename(missingPath)}`, "i"),
      );
    }
  });

  it("treats an absent content root as empty only while the ledger is empty", async (t) => {
    const empty = await compilerFixture(t);
    await rm(empty.contentRoot, { recursive: true });
    assert.deepEqual(
      await compileNurseryRhymePackages({ ...empty, runTool: fakeAudioRunner() }),
      [],
    );

    const protectedFixture = await compilerFixture(t, [{
      id: "alpha-v1",
      lineIds: ["alpha-v1-line-1"],
    }]);
    await rm(protectedFixture.contentRoot, { recursive: true });
    await assert.rejects(
      compileNurseryRhymePackages({
        ...protectedFixture,
        runTool: fakeAudioRunner(),
      }),
      /content.*missing|protected.*alpha-v1/i,
    );
  });
});

describe("compiler filesystem containment", () => {
  it("rejects package, manifest, and score symlinks", async (t) => {
    const packageFixture = await compilerFixture(t);
    const outsidePackage = path.join(packageFixture.root, "outside-package");
    await mkdir(outsidePackage);
    await symlink(outsidePackage, path.join(packageFixture.contentRoot, "linked-package"));
    await assert.rejects(
      compileNurseryRhymePackages({ ...packageFixture, runTool: fakeAudioRunner() }),
      /package.*symbolic link|symlink/i,
    );

    const manifestFixture = await compilerFixture(t);
    const { packageDir: manifestPackage } = await writePackage(
      manifestFixture.contentRoot,
      { slug: "manifest" },
    );
    const manifestPath = path.join(manifestPackage, "rhyme.json");
    const movedManifest = path.join(manifestFixture.root, "rhyme.json");
    await rename(manifestPath, movedManifest);
    await symlink(movedManifest, manifestPath);
    await assert.rejects(
      compileNurseryRhymePackages({ ...manifestFixture, runTool: fakeAudioRunner() }),
      /rhyme\.json.*symbolic link|symlink/i,
    );

    const scoreFixture = await compilerFixture(t);
    const { packageDir: scorePackage } = await writePackage(
      scoreFixture.contentRoot,
      { slug: "score" },
    );
    const scorePath = path.join(scorePackage, "score.musicxml");
    const movedScore = path.join(scoreFixture.root, "score.musicxml");
    await rename(scorePath, movedScore);
    await symlink(movedScore, scorePath);
    await assert.rejects(
      compileNurseryRhymePackages({ ...scoreFixture, runTool: fakeAudioRunner() }),
      /score\.musicxml.*symbolic link|symlink/i,
    );
  });

  it("rejects guide symlinks into a sibling package before audio inspection", async (t) => {
    const fixture = await compilerFixture(t);
    const { manifest, packageDir } = await writePackage(fixture.contentRoot, {
      order: 1,
      slug: "alpha",
    });
    const sibling = await writePackage(fixture.contentRoot, { order: 2, slug: "beta" });
    const guidePath = path.join(
      packageDir,
      ...manifest.scenes[0].lines[0].guide.split("/"),
    );
    const siblingGuide = path.join(
      sibling.packageDir,
      ...sibling.manifest.scenes[0].lines[0].guide.split("/"),
    );
    await rm(guidePath);
    await symlink(siblingGuide, guidePath);
    const calls = [];

    await assert.rejects(
      compileNurseryRhymePackages({ ...fixture, runTool: fakeAudioRunner(calls) }),
      /guide.*symbolic link|symlink/i,
    );
    assert.equal(calls.length, 0);
  });

  it("rejects guide symlinks outside the content root before audio inspection", async (t) => {
    const fixture = await compilerFixture(t);
    const { manifest, packageDir } = await writePackage(fixture.contentRoot, {
      slug: "alpha",
    });
    const guidePath = path.join(
      packageDir,
      ...manifest.scenes[0].lines[0].guide.split("/"),
    );
    const outsideGuide = path.join(fixture.root, "outside.mp3");
    await writeFile(outsideGuide, "outside guide");
    await rm(guidePath);
    await symlink(outsideGuide, guidePath);
    const calls = [];

    await assert.rejects(
      compileNurseryRhymePackages({ ...fixture, runTool: fakeAudioRunner(calls) }),
      /guide.*symbolic link|symlink/i,
    );
    assert.equal(calls.length, 0);
  });

  it("rejects realpath escapes through a linked guide directory before audio inspection", async (t) => {
    const fixture = await compilerFixture(t);
    const { manifest, packageDir } = await writePackage(fixture.contentRoot, {
      slug: "alpha",
    });
    const guidesDir = path.join(packageDir, "guides");
    const outsideGuides = path.join(fixture.root, "outside-guides");
    await rename(guidesDir, outsideGuides);
    await symlink(outsideGuides, guidesDir);
    const calls = [];

    await assert.rejects(
      compileNurseryRhymePackages({ ...fixture, runTool: fakeAudioRunner(calls) }),
      /guide.*outside|real path|realpath/i,
    );
    assert.equal(calls.length, 0);
    assert.ok(manifest.scenes[0].lines[0].guide.startsWith("guides/"));
  });
});

describe("append-only deployed ID ledger", () => {
  it("rejects reordered or prefixed protected rhymes in both modes without writes", async (t) => {
    const protectedIds = [
      { id: "alpha-v1", lineIds: ["alpha-v1-line-1"] },
      { id: "beta-v1", lineIds: ["beta-v1-line-1"] },
    ];
    for (const mutation of ["swap", "insert ahead"]) {
      const fixture = await generatorFixture(t, protectedIds);
      if (mutation === "insert ahead") {
        await writePackage(fixture.contentRoot, { order: 1, slug: "new-rhyme" });
      }
      await writePackage(fixture.contentRoot, {
        order: 2,
        slug: "alpha",
      });
      await writePackage(fixture.contentRoot, {
        order: mutation === "swap" ? 1 : 3,
        slug: "beta",
      });
      const ledgerBefore = await readFile(fixture.ledgerPath);
      const generatedBefore = await readFile(fixture.outputPath);

      for (const check of [false, true]) {
        await assert.rejects(
          runRhymeCatalogGenerator({
            check,
            rootDir: fixture.rootDir,
            runTool: fakeAudioRunner(),
          }),
          /protected.*rhyme.*order|ordered.*prefix|rhyme.*append/i,
        );
        assert.deepEqual(await readFile(fixture.ledgerPath), ledgerBefore);
        assert.deepEqual(await readFile(fixture.outputPath), generatedBefore);
      }
    }
  });

  it("rejects missing or renamed protected rhyme and line IDs in check and write modes", async (t) => {
    const protectedIds = [{
      id: "twinkle-twinkle-v1",
      lineIds: ["twinkle-twinkle-v1-line-1"],
    }];
    for (const renamed of ["rhyme", "line"]) {
      const fixture = await generatorFixture(t, protectedIds);
      await writePackage(fixture.contentRoot, {
        id: renamed === "rhyme" ? "renamed-v1" : "twinkle-twinkle-v1",
        lines: [lineFor("twinkle-twinkle", 1, {
          id: renamed === "line"
            ? "twinkle-twinkle-v1-line-renamed"
            : "twinkle-twinkle-v1-line-1",
        })],
        slug: "twinkle-twinkle",
      });
      const ledgerBefore = await readFile(fixture.ledgerPath, "utf8");
      const generatedBefore = await readFile(fixture.outputPath, "utf8");
      for (const check of [false, true]) {
        await assert.rejects(
          runRhymeCatalogGenerator({
            check,
            rootDir: fixture.rootDir,
            runTool: fakeAudioRunner(),
          }),
          /protected.*missing|deployed.*missing|renamed/i,
        );
      }
      assert.equal(await readFile(fixture.ledgerPath, "utf8"), ledgerBefore);
      assert.equal(await readFile(fixture.outputPath, "utf8"), generatedBefore);
    }
  });

  it("write mode appends a new rhyme and trailing line without rewriting prior IDs", async (t) => {
    const fixture = await generatorFixture(t);
    await writePackage(fixture.contentRoot, {
      lines: [lineFor("alpha", 1)],
      order: 1,
      slug: "alpha",
    });
    await runRhymeCatalogGenerator({
      check: false,
      rootDir: fixture.rootDir,
      runTool: fakeAudioRunner(),
    });

    await writePackage(fixture.contentRoot, {
      lines: [lineFor("alpha", 1), lineFor("alpha", 2)],
      order: 1,
      slug: "alpha",
    });
    await writePackage(fixture.contentRoot, { order: 2, slug: "beta" });
    await runRhymeCatalogGenerator({
      check: false,
      rootDir: fixture.rootDir,
      runTool: fakeAudioRunner(),
    });

    assert.deepEqual(
      JSON.parse(await readFile(fixture.ledgerPath, "utf8")),
      {
        schemaVersion: 1,
        rhymes: [
          {
            id: "alpha-v1",
            lineIds: ["alpha-v1-line-1", "alpha-v1-line-2"],
          },
          { id: "beta-v1", lineIds: ["beta-v1-line-1"] },
        ],
      },
    );
  });

  it("rejects non-trailing insertions ahead of protected line IDs", async (t) => {
    const fixture = await generatorFixture(t, [{
      id: "alpha-v1",
      lineIds: ["alpha-v1-line-1"],
    }]);
    await writePackage(fixture.contentRoot, {
      lines: [
        lineFor("alpha", 2, { id: "alpha-v1-line-new" }),
        lineFor("alpha", 1),
      ],
      slug: "alpha",
    });

    await assert.rejects(
      runRhymeCatalogGenerator({
        check: false,
        rootDir: fixture.rootDir,
        runTool: fakeAudioRunner(),
      }),
      /protected.*order|append.*line|line.*missing/i,
    );
  });

  it("check mode reports required ledger appends without changing either file", async (t) => {
    const fixture = await generatorFixture(t);
    await writePackage(fixture.contentRoot, { slug: "alpha" });
    const ledgerBefore = await readFile(fixture.ledgerPath, "utf8");
    const generatedBefore = await readFile(fixture.outputPath, "utf8");

    await assert.rejects(
      runRhymeCatalogGenerator({
        check: true,
        rootDir: fixture.rootDir,
        runTool: fakeAudioRunner(),
      }),
      /npm run generate:rhyme-catalog/,
    );
    assert.equal(await readFile(fixture.ledgerPath, "utf8"), ledgerBefore);
    assert.equal(await readFile(fixture.outputPath, "utf8"), generatedBefore);
  });

  it("validates the strict ledger shape before compiling or serializing", async (t) => {
    const fixture = await compilerFixture(t);
    await writeFile(
      fixture.ledgerPath,
      '{"schemaVersion":1,"rhymes":[],"unexpected":true}\n',
    );
    await assert.rejects(
      compileNurseryRhymePackages({ ...fixture, runTool: fakeAudioRunner() }),
      /ledger.*unexpected|unrecognized|strict/i,
    );
  });
});

describe("generated module serialization and generator modes", () => {
  it("serializes only stable JSON-compatible literals plus the warning and as const", () => {
    assert.equal(serializeGeneratedCatalog([]), EMPTY_GENERATED);
    const generated = serializeGeneratedCatalog([{ id: "alpha", values: [1, true, null] }]);
    assert.match(generated, /^\/\/ Generated by scripts\/generate-rhyme-catalog\.mjs\. Do not edit\.\n/);
    assert.match(generated, /export const GENERATED_DUB_DEFINITIONS = \[\n/);
    assert.match(generated, /\] as const;\n$/);
    assert.doesNotMatch(generated, /undefined|NaN|Infinity|function|Object\.freeze/);
  });

  it("writes deterministic bytes across repeated generator runs", async (t) => {
    const fixture = await generatorFixture(t);
    await writePackage(fixture.contentRoot, { slug: "alpha" });
    await runRhymeCatalogGenerator({
      check: false,
      rootDir: fixture.rootDir,
      runTool: fakeAudioRunner(),
    });
    const firstLedger = await readFile(fixture.ledgerPath);
    const firstGenerated = await readFile(fixture.outputPath);

    await runRhymeCatalogGenerator({
      check: false,
      rootDir: fixture.rootDir,
      runTool: fakeAudioRunner(),
    });
    assert.deepEqual(await readFile(fixture.ledgerPath), firstLedger);
    assert.deepEqual(await readFile(fixture.outputPath), firstGenerated);
  });

  it("reports corrupted generated output in check mode without rewriting registry or ledger", async (t) => {
    const fixture = await generatorFixture(t);
    await writePackage(fixture.contentRoot, { slug: "alpha" });
    await runRhymeCatalogGenerator({
      check: false,
      rootDir: fixture.rootDir,
      runTool: fakeAudioRunner(),
    });
    const ledgerBefore = await readFile(fixture.ledgerPath);
    const generated = await readFile(fixture.outputPath, "utf8");
    const corruptedGenerated = `${generated}\n// corrupted\n`;
    await writeFile(fixture.outputPath, corruptedGenerated);

    await assert.rejects(
      runRhymeCatalogGenerator({
        check: true,
        rootDir: fixture.rootDir,
        runTool: fakeAudioRunner(),
      }),
      /generated-rhyme-catalog\.ts.*npm run generate:rhyme-catalog/,
    );
    assert.equal(await readFile(fixture.outputPath, "utf8"), corruptedGenerated);
    assert.deepEqual(await readFile(fixture.ledgerPath), ledgerBefore);
  });

  it("the CLI rejects every argument except --check", async () => {
    await assert.rejects(
      execFileAsync(
        process.execPath,
        [path.join(repositoryRoot, "scripts", "generate-rhyme-catalog.mjs"), "--write"],
        { cwd: repositoryRoot },
      ),
      /unknown|usage|--check/i,
    );
  });
});

describe("production legacy-compatible nursery-rhyme packages", () => {
  it("preserves the protected six-rhyme runtime and guide-byte contract", async () => {
    const expectedCatalog = snapshot.catalog.map((definition) => ({
      ...definition,
      phraseDurationsMs: expandedLegacyPhraseDurations(definition),
    }));
    assert.deepEqual(generatedCatalogContract(GENERATED_DUB_DEFINITIONS), expectedCatalog);

    const guides = await Promise.all(
      GENERATED_DUB_DEFINITIONS.flatMap((definition) => definition.guides).map(
        async ({ id, src, text }) => ({
          id,
          text,
          sha256: createHash("sha256")
            .update(await readFile(path.join(repositoryRoot, "public", src.slice(1))))
            .digest("hex"),
        }),
      ),
    );
    assert.deepEqual(guides, snapshot.guides);
  });

  it("contains the complete deterministic production inventory", () => {
    assert.equal(GENERATED_DUB_DEFINITIONS.length, 6);
    assert.equal(
      GENERATED_DUB_DEFINITIONS.reduce((count, definition) => count + definition.lines.length, 0),
      81,
    );
    assert.equal(
      new Set(GENERATED_DUB_DEFINITIONS.flatMap((definition) =>
        definition.guides.map(({ id }) => id))).size,
      59,
    );
    for (const definition of GENERATED_DUB_DEFINITIONS) {
      for (const line of definition.lines) {
        assert.equal(line.guidePeakBars.length, 32, line.id);
        assert.ok(
          line.guidePeakBars.every((bar) => Number.isFinite(bar) && bar >= 0 && bar <= 1),
          line.id,
        );
      }
    }

    const ducks = GENERATED_DUB_DEFINITIONS[0];
    assert.equal(ducks.sceneTitles.length, 6);
    assert.equal(ducks.linesPerScene, 4);
    assert.equal(ducks.lines.length, 6 * 4);

    const oldMacDonald = GENERATED_DUB_DEFINITIONS[1];
    assert.equal(oldMacDonald.sceneTitles.length, 5);
    assert.equal(oldMacDonald.linesPerScene, 7);
    assert.equal(oldMacDonald.lines.length, 5 * 7);
    assert.deepEqual(
      oldMacDonald.music.linePhrases.map(({ durationMs }) => durationMs),
      Array.from({ length: 5 }, () => [8_000, 8_000, 2_000, 2_000, 2_000, 2_000, 8_000]).flat(),
    );
  });
});
