import {
  lstat,
  readFile,
  readdir,
  realpath,
} from "node:fs/promises";
import path from "node:path";
import { inspectGuideAudio } from "./audio.mjs";
import { parseRhymeManifest, resolvePackageAsset } from "./manifest.mjs";
import { compileMusicXml } from "./musicxml.mjs";

const ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const GENERATED_WARNING =
  "// Generated by scripts/generate-rhyme-catalog.mjs. Do not edit.\n";

function isPlainObject(value) {
  return value !== null
    && typeof value === "object"
    && !Array.isArray(value)
    && Object.getPrototypeOf(value) === Object.prototype;
}

function assertExactKeys(value, keys, sourcePath, field) {
  if (!isPlainObject(value)) {
    throw new Error(`${sourcePath}:${field}: must be an object`);
  }
  const expected = new Set(keys);
  const unexpected = Object.keys(value).find((key) => !expected.has(key));
  if (unexpected) {
    throw new Error(`${sourcePath}:${field}: unexpected ledger field ${unexpected}`);
  }
  const missing = keys.find((key) => !Object.hasOwn(value, key));
  if (missing) {
    throw new Error(`${sourcePath}:${field}: missing ledger field ${missing}`);
  }
}

function validateDeploymentLedger(value, ledgerPath) {
  assertExactKeys(value, ["schemaVersion", "rhymes"], ledgerPath, "ledger");
  if (value.schemaVersion !== 1) {
    throw new Error(`${ledgerPath}:ledger.schemaVersion: must equal 1`);
  }
  if (!Array.isArray(value.rhymes)) {
    throw new Error(`${ledgerPath}:ledger.rhymes: must be an array`);
  }

  const rhymeIds = new Set();
  const rhymes = value.rhymes.map((rhyme, rhymeIndex) => {
    const field = `ledger.rhymes[${rhymeIndex}]`;
    assertExactKeys(rhyme, ["id", "lineIds"], ledgerPath, field);
    if (typeof rhyme.id !== "string" || !ID_PATTERN.test(rhyme.id)) {
      throw new Error(`${ledgerPath}:${field}.id: must be lowercase kebab-case`);
    }
    if (rhymeIds.has(rhyme.id)) {
      throw new Error(`${ledgerPath}:${field}.id: duplicate deployed rhyme id ${rhyme.id}`);
    }
    rhymeIds.add(rhyme.id);
    if (!Array.isArray(rhyme.lineIds) || rhyme.lineIds.length === 0) {
      throw new Error(`${ledgerPath}:${field}.lineIds: must contain at least one line id`);
    }
    const lineIds = new Set();
    for (const [lineIndex, lineId] of rhyme.lineIds.entries()) {
      if (typeof lineId !== "string" || !ID_PATTERN.test(lineId)) {
        throw new Error(
          `${ledgerPath}:${field}.lineIds[${lineIndex}]: must be lowercase kebab-case`,
        );
      }
      if (lineIds.has(lineId)) {
        throw new Error(
          `${ledgerPath}:${field}.lineIds[${lineIndex}]: duplicate deployed line id ${lineId}`,
        );
      }
      lineIds.add(lineId);
    }
    return { id: rhyme.id, lineIds: [...rhyme.lineIds] };
  });
  return { schemaVersion: 1, rhymes };
}

export async function readRhymeDeploymentLedger(ledgerPath) {
  let source;
  try {
    source = await readFile(ledgerPath, "utf8");
  } catch (error) {
    throw new Error(`${ledgerPath}: deployment ledger is missing or unreadable (${error.message})`);
  }
  let value;
  try {
    value = JSON.parse(source);
  } catch (error) {
    throw new Error(`${ledgerPath}: deployment ledger is not valid JSON (${error.message})`);
  }
  return validateDeploymentLedger(value, ledgerPath);
}

function pathIsInside(parent, child) {
  const relative = path.relative(parent, child);
  return relative.length > 0
    && relative !== ".."
    && !relative.startsWith(`..${path.sep}`)
    && !path.isAbsolute(relative);
}

async function inspectRegularPath(filePath, packageRealPath, contentRealPath, label) {
  let fileStat;
  try {
    fileStat = await lstat(filePath);
  } catch (error) {
    throw new Error(`${filePath}: ${label} file is missing or unreadable (${error.message})`);
  }
  if (fileStat.isSymbolicLink()) {
    throw new Error(`${filePath}: ${label} file must not be a symbolic link`);
  }
  if (!fileStat.isFile()) {
    throw new Error(`${filePath}: ${label} must be a regular file`);
  }
  const realFilePath = await realpath(filePath);
  if (
    !pathIsInside(packageRealPath, realFilePath)
    || !pathIsInside(contentRealPath, realFilePath)
  ) {
    throw new Error(`${filePath}: ${label} real path resolves outside its package`);
  }
  return realFilePath;
}

async function inspectContentRoot(contentRoot, ledger) {
  let rootStat;
  try {
    rootStat = await lstat(contentRoot);
  } catch (error) {
    if (error.code === "ENOENT" && ledger.rhymes.length === 0) return null;
    if (error.code === "ENOENT") {
      throw new Error(
        `${contentRoot}: content root is missing while the deployment ledger protects ${ledger.rhymes[0].id}`,
      );
    }
    throw new Error(`${contentRoot}: content root is unreadable (${error.message})`);
  }
  if (rootStat.isSymbolicLink()) {
    throw new Error(`${contentRoot}: content root must not be a symbolic link`);
  }
  if (!rootStat.isDirectory()) {
    throw new Error(`${contentRoot}: content root must be a directory`);
  }
  return realpath(contentRoot);
}

async function discoverPackages(contentRoot, contentRealPath) {
  const entries = (await readdir(contentRoot, { withFileTypes: true }))
    .sort((left, right) => left.name.localeCompare(right.name));
  const packages = [];
  for (const entry of entries) {
    const packagePath = path.join(contentRoot, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`${packagePath}: package must not be a symbolic link`);
    }
    if (!entry.isDirectory()) {
      throw new Error(`${packagePath}: content root entries must be package directories`);
    }
    if (!ID_PATTERN.test(entry.name)) {
      throw new Error(`${packagePath}: package directory must be lowercase kebab-case`);
    }

    const packageStat = await lstat(packagePath);
    if (packageStat.isSymbolicLink() || !packageStat.isDirectory()) {
      throw new Error(`${packagePath}: package must be a non-symlink directory`);
    }
    const packageRealPath = await realpath(packagePath);
    if (!pathIsInside(contentRealPath, packageRealPath)) {
      throw new Error(`${packagePath}: package real path resolves outside the content root`);
    }

    const manifestPath = path.join(packagePath, "rhyme.json");
    await inspectRegularPath(
      manifestPath,
      packageRealPath,
      contentRealPath,
      "manifest",
    );
    let manifestValue;
    try {
      manifestValue = JSON.parse(await readFile(manifestPath, "utf8"));
    } catch (error) {
      throw new Error(`${manifestPath}: manifest is not valid JSON (${error.message})`);
    }
    const manifest = parseRhymeManifest(manifestValue, manifestPath);
    const scorePath = resolvePackageAsset(packagePath, manifest.score.src, "score.src");
    const flatLines = manifest.scenes.flatMap((scene) => scene.lines);
    const guidePaths = flatLines.map((line, lineIndex) => ({
      line,
      path: resolvePackageAsset(packagePath, line.guide, `lines[${lineIndex}].guide`),
    }));
    packages.push({
      directoryName: entry.name,
      flatLines,
      guidePaths,
      manifest,
      manifestPath,
      packagePath,
      packageRealPath,
      scorePath,
    });
  }
  return packages;
}

function assertUniquePackages(packages) {
  const orders = new Map();
  const ids = new Map();
  const slugs = new Map();
  const guidePaths = new Map();
  const guideStems = new Map();
  for (const currentPackage of packages) {
    const { manifest, manifestPath } = currentPackage;
    for (const [name, value, seen] of [
      ["order", manifest.order, orders],
      ["rhyme id", manifest.id, ids],
      ["slug/route", manifest.slug, slugs],
    ]) {
      if (seen.has(value)) {
        throw new Error(
          `${manifestPath}: duplicate global ${name} ${value}; first declared by ${seen.get(value)}`,
        );
      }
      seen.set(value, manifestPath);
    }

    for (const { line, path: guidePath } of currentPackage.guidePaths) {
      const priorText = guidePaths.get(guidePath);
      if (priorText !== undefined && priorText !== line.text) {
        throw new Error(
          `${manifestPath}: guide ${line.guide} is reused with different exact text`,
        );
      }
      guidePaths.set(guidePath, line.text);

      const stem = path.basename(guidePath, ".mp3");
      const priorPath = guideStems.get(stem);
      if (priorPath !== undefined && priorPath !== guidePath) {
        throw new Error(
          `${manifestPath}: duplicate global guide stem ${stem} at ${guidePath}; first declared at ${priorPath}`,
        );
      }
      guideStems.set(stem, guidePath);
    }
  }
}

async function preflightPackageAssets(packages, contentRealPath) {
  for (const currentPackage of packages) {
    await inspectRegularPath(
      currentPackage.scorePath,
      currentPackage.packageRealPath,
      contentRealPath,
      "score",
    );
    for (const guide of currentPackage.guidePaths) {
      guide.realPath = await inspectRegularPath(
        guide.path,
        currentPackage.packageRealPath,
        contentRealPath,
        "guide",
      );
    }
  }
}

function assertProtectedIds(catalog, ledger, ledgerPath) {
  const definitions = new Map(catalog.map((definition) => [definition.id, definition]));
  for (const protectedRhyme of ledger.rhymes) {
    const definition = definitions.get(protectedRhyme.id);
    if (!definition) {
      throw new Error(
        `${ledgerPath}: protected deployed rhyme id ${protectedRhyme.id} is missing or renamed`,
      );
    }
    const lineIds = definition.lines.map(({ id }) => id);
    for (const [lineIndex, protectedLineId] of protectedRhyme.lineIds.entries()) {
      if (lineIds[lineIndex] !== protectedLineId) {
        throw new Error(
          `${ledgerPath}: protected deployed line id ${protectedLineId} is missing, renamed, or reordered; new line IDs may only be appended`,
        );
      }
    }
  }
}

function staticGuideSrc(directoryName, relativePath) {
  return `/assets/nursery-rhymes/${directoryName}/${relativePath}`;
}

async function compileDefinitions(packages, runTool) {
  for (const currentPackage of packages) {
    const xml = await readFile(currentPackage.scorePath, "utf8");
    currentPackage.score = compileMusicXml({
      manifest: currentPackage.manifest,
      sourcePath: currentPackage.scorePath,
      xml,
    });
  }

  const audioInspections = new Map();
  const definitions = [];
  for (const currentPackage of packages) {
    const { manifest, score } = currentPackage;
    const guides = new Map();
    const lines = [];
    for (const [lineIndex, compiledLine] of score.lines.entries()) {
      const authoredLine = currentPackage.flatLines[lineIndex];
      const guide = currentPackage.guidePaths[lineIndex];
      const inspectionKey = `${guide.realPath}\0${compiledLine.durationMs}`;
      let inspection = audioInspections.get(inspectionKey);
      if (!inspection) {
        inspection = await inspectGuideAudio({
          filePath: guide.path,
          runTool,
          timelineDurationMs: compiledLine.durationMs,
        });
        audioInspections.set(inspectionKey, inspection);
      }
      const guideAudioId = path.basename(guide.path, ".mp3");
      const guideAudioSrc = staticGuideSrc(currentPackage.directoryName, authoredLine.guide);
      const priorGuide = guides.get(guide.path);
      if (priorGuide && priorGuide.durationMs !== inspection.durationMs) {
        throw new Error(`${guide.path}: guide duration changed between line inspections`);
      }
      if (!priorGuide) {
        guides.set(guide.path, {
          id: guideAudioId,
          src: guideAudioSrc,
          text: authoredLine.text,
          durationMs: inspection.durationMs,
        });
      }
      lines.push({
        id: compiledLine.id,
        text: compiledLine.text,
        cueMs: compiledLine.cueMs,
        durationMs: compiledLine.durationMs,
        guideAudioId,
        guideAudioSrc,
        guidePeakBars: inspection.peakBars,
        words: compiledLine.words,
      });
    }

    const lineArtwork = currentPackage.flatLines.map(({ artwork: value }) => value ?? null);
    definitions.push({
      id: manifest.id,
      route: `/dubs/${manifest.slug}`,
      title: manifest.title,
      durationMs: score.durationMs,
      finalCueTailMs: score.durationMs - score.lines.at(-1).cueMs,
      linesPerScene: manifest.scenes[0].lines.length,
      countInBeats: manifest.countInBeats,
      countInMidi: manifest.countInMidi,
      sceneTitles: manifest.scenes.map(({ title }) => title),
      sceneArtwork: manifest.scenes.map(({ artwork: value }) => value),
      lineArtwork: lineArtwork.every((value) => value === null) ? null : lineArtwork,
      lines,
      music: {
        countInBeatMs: score.countInBeatMs,
        countInDurationMs: score.countInDurationMs,
        linePhrases: score.lines.map(({ durationMs, notes, playbackNotes }) => ({
          durationMs,
          notes,
          playbackNotes,
        })),
        outroNotes: score.outroNotes,
        volume: manifest.score.volume,
      },
      guides: [...guides.values()],
    });
  }
  return definitions;
}

/** Compile every package into deterministic JSON-compatible runtime literals. */
export async function compileNurseryRhymePackages({
  contentRoot,
  ledgerPath,
  runTool,
}) {
  const ledger = await readRhymeDeploymentLedger(ledgerPath);
  const contentRealPath = await inspectContentRoot(contentRoot, ledger);
  if (contentRealPath === null) return [];

  const packages = await discoverPackages(contentRoot, contentRealPath);
  assertUniquePackages(packages);
  await preflightPackageAssets(packages, contentRealPath);
  packages.sort(
    (left, right) => left.manifest.order - right.manifest.order
      || left.manifest.slug.localeCompare(right.manifest.slug),
  );
  const catalog = await compileDefinitions(packages, runTool);
  assertProtectedIds(catalog, ledger, ledgerPath);
  return catalog;
}

export function appendCatalogToDeploymentLedger(catalog, ledger, ledgerPath) {
  const validatedLedger = validateDeploymentLedger(ledger, ledgerPath);
  assertProtectedIds(catalog, validatedLedger, ledgerPath);
  const definitions = new Map(catalog.map((definition) => [definition.id, definition]));
  const rhymes = validatedLedger.rhymes.map((protectedRhyme) => {
    const lineIds = definitions.get(protectedRhyme.id).lines.map(({ id }) => id);
    return {
      id: protectedRhyme.id,
      lineIds: [
        ...protectedRhyme.lineIds,
        ...lineIds.slice(protectedRhyme.lineIds.length),
      ],
    };
  });
  const protectedIds = new Set(rhymes.map(({ id }) => id));
  for (const definition of catalog) {
    if (!protectedIds.has(definition.id)) {
      rhymes.push({
        id: definition.id,
        lineIds: definition.lines.map(({ id }) => id),
      });
    }
  }
  return { schemaVersion: 1, rhymes };
}

export function serializeDeploymentLedger(ledger) {
  const validated = validateDeploymentLedger(ledger, "deployment ledger");
  return validated.rhymes.length === 0
    ? '{ "schemaVersion": 1, "rhymes": [] }\n'
    : `${JSON.stringify(validated, null, 2)}\n`;
}

export function serializeGeneratedCatalog(catalog) {
  if (!Array.isArray(catalog)) {
    throw new TypeError("The compiled nursery rhyme catalog must be an array.");
  }
  return `${GENERATED_WARNING}export const GENERATED_DUB_DEFINITIONS = ${
    JSON.stringify(catalog, null, 2)
  } as const;\n`;
}
