import { createHash } from "node:crypto";
import { constants } from "node:fs";
import { lstat, open, readdir, realpath } from "node:fs/promises";
import path from "node:path";
import {
  parseNotoAssetManifest,
  parseWordGameManifest,
} from "./manifest.mjs";

const GENERATED_WARNING =
  "// Generated by scripts/generate-word-game-catalog.mjs. Do not edit.\n";

function compareCodeUnits(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function portableRelativePath(parent, child) {
  return path.relative(parent, child).split(path.sep).join("/");
}

function pathIsInside(parent, child) {
  const relative = path.relative(parent, child);
  return relative.length > 0
    && relative !== ".."
    && !relative.startsWith(`..${path.sep}`)
    && !path.isAbsolute(relative);
}

async function inspectDirectory(directoryPath, label, parentRealPath) {
  let stat;
  try {
    stat = await lstat(directoryPath);
  } catch (error) {
    throw new Error(`${directoryPath}: ${label} is missing or unreadable (${error.message})`);
  }
  if (stat.isSymbolicLink()) {
    throw new Error(`${directoryPath}: ${label} must not be a symbolic link`);
  }
  if (!stat.isDirectory()) {
    throw new Error(`${directoryPath}: ${label} must be a directory`);
  }
  const realPath = await realpath(directoryPath);
  if (parentRealPath && !pathIsInside(parentRealPath, realPath)) {
    throw new Error(`${directoryPath}: ${label} resolves outside the repository root`);
  }
  return realPath;
}

async function inspectRegularFile(filePath, label, approvedRealPath) {
  let stat;
  try {
    stat = await lstat(filePath);
  } catch (error) {
    throw new Error(`${filePath}: ${label} is missing or unreadable (${error.message})`, {
      cause: error,
    });
  }
  if (stat.isSymbolicLink()) {
    throw new Error(`${filePath}: ${label} must not be a symbolic link`);
  }
  if (!stat.isFile()) {
    throw new Error(`${filePath}: ${label} must be a regular file`);
  }
  const realPath = await realpath(filePath);
  if (!pathIsInside(approvedRealPath, realPath)) {
    throw new Error(`${filePath}: ${label} resolves outside its approved root`);
  }
  return realPath;
}

async function readValidatedFile(filePath, label, approvedRealPath, openFile, encoding) {
  await inspectRegularFile(filePath, label, approvedRealPath);
  let handle;
  try {
    handle = await openFile(filePath, constants.O_RDONLY | constants.O_NOFOLLOW);
  } catch (error) {
    throw new Error(`${filePath}: ${label} changed before it could be opened safely`, {
      cause: error,
    });
  }
  try {
    if (!(await handle.stat()).isFile()) {
      throw new Error(`${filePath}: opened ${label} must be a regular file`);
    }
    return await handle.readFile(encoding);
  } finally {
    await handle.close();
  }
}

async function readJsonFile(filePath, label, approvedRealPath, openFile) {
  const source = await readValidatedFile(filePath, label, approvedRealPath, openFile, "utf8");
  try {
    return JSON.parse(source);
  } catch (error) {
    throw new Error(`${filePath}: ${label} is not valid JSON (${error.message})`);
  }
}

function duplicate(values, key) {
  const seen = new Set();
  for (const value of values) {
    const identity = value[key];
    if (seen.has(identity)) return identity;
    seen.add(identity);
  }
  return null;
}

function assertRawTierIds(value, sourcePath) {
  if (!Array.isArray(value?.tiers)) return;
  const duplicateId = duplicate(value.tiers, "id");
  if (duplicateId !== null) {
    throw new Error(`${sourcePath}: duplicate tier id ${duplicateId}`);
  }
}

async function discoverCategories(categoryRoot, categoryRealPath, openFile) {
  const entries = (await readdir(categoryRoot, { withFileTypes: true }))
    .sort((left, right) => compareCodeUnits(left.name, right.name));
  const packages = [];
  for (const entry of entries) {
    const sourcePath = path.join(categoryRoot, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`${sourcePath}: category file must not be a symbolic link`);
    }
    if (!entry.isFile() || path.extname(entry.name) !== ".json") {
      throw new Error(`${sourcePath}: unexpected category entry; expected a regular .json file`);
    }
    const value = await readJsonFile(sourcePath, "category file", categoryRealPath, openFile);
    assertRawTierIds(value, sourcePath);
    packages.push({
      filenameId: path.basename(entry.name, ".json"),
      manifest: parseWordGameManifest(value, sourcePath),
      sourcePath,
    });
  }
  return packages;
}

function assertUniqueCategories(packages) {
  const ids = new Map();
  const orders = new Map();
  for (const currentPackage of packages) {
    for (const [label, value, seen] of [
      ["category id", currentPackage.manifest.id, ids],
      ["category order", currentPackage.manifest.order, orders],
    ]) {
      if (seen.has(value)) {
        throw new Error(
          `${currentPackage.sourcePath}: duplicate ${label} ${value}; first declared by ${seen.get(value)}`,
        );
      }
      seen.set(value, currentPackage.sourcePath);
    }
  }
  for (const currentPackage of packages) {
    if (currentPackage.filenameId !== currentPackage.manifest.id) {
      throw new Error(
        `${currentPackage.sourcePath}: category filename ${currentPackage.filenameId} must match category id ${currentPackage.manifest.id}`,
      );
    }
  }
}

function assertUniqueIds(values, label, sourcePath) {
  const duplicateId = duplicate(values, "id");
  if (duplicateId !== null) {
    throw new Error(`${sourcePath}: duplicate ${label} id ${duplicateId}`);
  }
}

function capitalizedLabel(label) {
  return `${label[0].toUpperCase()}${label.slice(1)}.`;
}

function validateCategoryReferences(currentPackage, assetById, audioById, usedAssetIds) {
  const { manifest, sourcePath } = currentPackage;
  assertUniqueIds(manifest.items, "item", sourcePath);
  assertUniqueIds(manifest.tiers, "tier", sourcePath);
  const itemById = new Map(manifest.items.map((item) => [item.id, item]));
  if (!itemById.has(manifest.coverItemId)) {
    throw new Error(`${sourcePath}: coverItemId ${manifest.coverItemId} does not reference an item`);
  }

  const quizzes = manifest.tiers.flatMap(({ quizzes: tierQuizzes }) => tierQuizzes);
  assertUniqueIds(quizzes, "quiz", sourcePath);
  const targetedItems = new Set();
  for (const quiz of quizzes) {
    assertUniqueIds(quiz.questions, "question", sourcePath);
    const quizTargets = new Set();
    for (const question of quiz.questions) {
      const target = itemById.get(question.targetId);
      if (!target) {
        throw new Error(`${sourcePath}: question ${question.id} target ${question.targetId} is missing`);
      }
      if (quizTargets.has(question.targetId)) {
        throw new Error(`${sourcePath}: quiz ${quiz.id} target ${question.targetId} must appear once`);
      }
      quizTargets.add(question.targetId);
      targetedItems.add(question.targetId);
      for (const choiceId of question.choiceIds) {
        if (!itemById.has(choiceId)) {
          throw new Error(`${sourcePath}: question ${question.id} choice ${choiceId} is missing`);
        }
      }
      if (!question.prompt.startsWith(capitalizedLabel(target.label))) {
        throw new Error(
          `${sourcePath}: question ${question.id} prompt must begin with ${capitalizedLabel(target.label)}`,
        );
      }
      if (!question.success.includes(target.audio.text)) {
        throw new Error(
          `${sourcePath}: question ${question.id} success must contain the exact teaching text`,
        );
      }
    }
  }

  for (const item of manifest.items) {
    if (!targetedItems.has(item.id)) {
      throw new Error(`${sourcePath}: unused item ${item.id}; item is never targeted`);
    }
    const priorText = audioById.get(item.audio.id);
    if (priorText !== undefined) {
      if (priorText !== item.audio.text) {
        throw new Error(`${sourcePath}: audio id ${item.audio.id} is reused with different text`);
      }
      throw new Error(`${sourcePath}: duplicate global audio id ${item.audio.id}`);
    }
    audioById.set(item.audio.id, item.audio.text);
    if (item.visual.kind === "noto-svg") {
      if (!assetById.has(item.visual.assetId)) {
        throw new Error(`${sourcePath}: Noto asset ${item.visual.assetId} is not listed`);
      }
      usedAssetIds.add(item.visual.assetId);
    }
  }
}

function validateAssetRecords(assetManifest, assetManifestPath) {
  assertUniqueIds(assetManifest.assets, "Noto asset", assetManifestPath);
  const publicPaths = new Set();
  const upstreamPaths = new Set();
  for (const asset of assetManifest.assets) {
    const filename = `emoji_u${asset.id}.svg`;
    const expectedPublicPath = `/assets/word-games/noto/${filename}`;
    const expectedUpstreamPath = `svg/${filename}`;
    if (asset.publicPath !== expectedPublicPath) {
      throw new Error(
        `${assetManifestPath}: asset ${asset.id} publicPath must stay within the approved Noto root as ${expectedPublicPath}`,
      );
    }
    if (asset.upstreamPath !== expectedUpstreamPath) {
      throw new Error(
        `${assetManifestPath}: asset ${asset.id} upstreamPath must equal ${expectedUpstreamPath}`,
      );
    }
    for (const [label, value, seen] of [
      ["publicPath", asset.publicPath, publicPaths],
      ["upstreamPath", asset.upstreamPath, upstreamPaths],
    ]) {
      if (seen.has(value)) {
        throw new Error(`${assetManifestPath}: duplicate Noto ${label} ${value}`);
      }
      seen.add(value);
    }
  }
  return new Map(assetManifest.assets.map((asset) => [asset.id, asset]));
}

async function validateNotoFiles({ assetManifest, notoRoot, notoRealPath, openFile }) {
  const listedFilenames = new Set(assetManifest.assets.map(({ id }) => `emoji_u${id}.svg`));
  const entries = (await readdir(notoRoot, { withFileTypes: true }))
    .sort((left, right) => compareCodeUnits(left.name, right.name));
  for (const entry of entries) {
    const filePath = path.join(notoRoot, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`${filePath}: Noto SVG must not be a symbolic link`);
    }
    if (listedFilenames.has(entry.name) && !entry.isFile()) {
      throw new Error(`${filePath}: Noto SVG must be a regular file`);
    }
    if (!entry.isFile() || !listedFilenames.has(entry.name)) {
      throw new Error(`${filePath}: unexpected Noto file ${entry.name}`);
    }
  }
  for (const asset of assetManifest.assets) {
    const filePath = path.join(notoRoot, `emoji_u${asset.id}.svg`);
    const svg = await readValidatedFile(filePath, "Noto SVG", notoRealPath, openFile);
    const actualHash = createHash("sha256").update(svg).digest("hex");
    if (actualHash !== asset.sha256) {
      throw new Error(`${filePath}: SVG SHA-256 mismatch for Noto asset ${asset.id}`);
    }
  }
}

function compileAudio(audio) {
  return { ...audio, source: `/assets/audio/${audio.id}.mp3` };
}

function compileCategory(manifest, assetById) {
  return {
    ...manifest,
    items: manifest.items.map((item) => ({
      ...item,
      audio: compileAudio(item.audio),
      visual: item.visual.kind === "swatch"
        ? { ...item.visual }
        : { kind: "image", src: assetById.get(item.visual.assetId).publicPath },
    })),
  };
}

function plannerLine(id, text) {
  return {
    id,
    lang: "en-US",
    speaker: "narrator",
    src: `/assets/audio/${id}.mp3`,
    text,
    ttsText: `[bright, playful teaching delivery for a young child] ${text}`,
    voiceStyle: "energetic-character",
  };
}

async function inspectAudio(audioRoot, audioRealPath, audioById, rootDir, allowMissingAudio) {
  const missingFiles = [];
  for (const id of [...audioById.keys()].sort(compareCodeUnits)) {
    const filePath = path.join(audioRoot, `${id}.mp3`);
    try {
      await inspectRegularFile(filePath, "audio file", audioRealPath);
    } catch (error) {
      if (allowMissingAudio && error.cause?.code === "ENOENT") {
        missingFiles.push(portableRelativePath(rootDir, filePath));
        continue;
      }
      throw error;
    }
  }
  return missingFiles.sort(compareCodeUnits);
}

async function compile({
  rootDir,
  categoryRoot = path.join(rootDir, "content", "word-games", "categories"),
  assetManifestPath = path.join(rootDir, "content", "word-games", "noto-assets.json"),
  publicRoot = path.join(rootDir, "public"),
  audioRoot = path.join(publicRoot, "assets", "audio"),
  openFile = open,
}, allowMissingAudio) {
  const rootRealPath = await inspectDirectory(rootDir, "repository root");
  const categoryRealPath = await inspectDirectory(categoryRoot, "category root", rootRealPath);
  const publicRealPath = await inspectDirectory(publicRoot, "public root", rootRealPath);
  const audioRealPath = await inspectDirectory(audioRoot, "audio root", publicRealPath);
  if (!pathIsInside(rootRealPath, audioRealPath)) {
    throw new Error(`${audioRoot}: audio root resolves outside the repository root`);
  }
  if (!pathIsInside(path.resolve(rootDir), path.resolve(assetManifestPath))) {
    throw new Error(`${assetManifestPath}: asset manifest path is outside the repository root`);
  }
  const notoRoot = path.join(publicRoot, "assets", "word-games", "noto");
  const notoRealPath = await inspectDirectory(notoRoot, "Noto root", publicRealPath);
  const licensePath = path.join(rootDir, "third_party", "noto-emoji-svg-LICENSE");
  await inspectRegularFile(licensePath, "Noto license", rootRealPath);

  const assetManifestValue = await readJsonFile(
    assetManifestPath,
    "Noto asset manifest",
    rootRealPath,
    openFile,
  );
  const assetManifest = parseNotoAssetManifest(assetManifestValue, assetManifestPath);
  const assetById = validateAssetRecords(assetManifest, assetManifestPath);
  await validateNotoFiles({ assetManifest, notoRoot, notoRealPath, openFile });

  const packages = await discoverCategories(categoryRoot, categoryRealPath, openFile);
  assertUniqueCategories(packages);
  const audioById = new Map();
  const usedAssetIds = new Set();
  for (const currentPackage of packages) {
    validateCategoryReferences(currentPackage, assetById, audioById, usedAssetIds);
  }
  for (const asset of assetManifest.assets) {
    if (!usedAssetIds.has(asset.id)) {
      throw new Error(`${assetManifestPath}: unused Noto asset ${asset.id}`);
    }
  }

  const missingFiles = await inspectAudio(
    audioRoot,
    audioRealPath,
    audioById,
    rootDir,
    allowMissingAudio,
  );
  packages.sort(
    (left, right) => left.manifest.order - right.manifest.order
      || compareCodeUnits(left.manifest.id, right.manifest.id),
  );
  return {
    compiled: {
      assets: assetManifest.assets.map((asset) => ({ ...asset })),
      categories: packages.map(({ manifest }) => compileCategory(manifest, assetById)),
    },
    lines: [...audioById.entries()]
      .map(([id, text]) => plannerLine(id, text))
      .sort((left, right) => compareCodeUnits(left.id, right.id)),
    missingFiles,
  };
}

/** Compile every word-game package into deterministic JSON-compatible literals. */
export async function compileWordGamePackages(paths) {
  return (await compile(paths, false)).compiled;
}

/** Validate authored content while inventorying missing saved item cues. */
export async function planWordGameAudio({ rootDir }) {
  const { lines, missingFiles } = await compile({ rootDir }, true);
  return { lines, missingFiles };
}

export function serializeGeneratedWordGameCatalog(compiled) {
  if (!compiled || !Array.isArray(compiled.categories)) {
    throw new TypeError("The compiled word-game catalog must contain categories.");
  }
  return `${GENERATED_WARNING}export const GENERATED_WORD_GAME_CATALOG = ${
    JSON.stringify(compiled.categories, null, 2)
  } as const;\n`;
}
