import { createHash } from "node:crypto";
import { constants } from "node:fs";
import { lstat, open, readdir, realpath } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import {
  parseIllustrationAssetManifest,
  parseWordGameManifest,
  parseWordGamePlayerManifest,
} from "./manifest.mjs";

const GENERATED_WARNING =
  "// Generated by scripts/generate-word-game-catalog.mjs. Do not edit.\n";

function compareCodeUnits(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function portableRelativePath(parent, child) {
  return path.relative(parent, child).split(path.sep).join("/");
}

function pathIsInside(parent, child) {
  const relative = path.relative(parent, child);
  return relative.length > 0
    && relative !== ".."
    && !relative.startsWith(`..${path.sep}`)
    && !path.isAbsolute(relative);
}

async function inspectDirectory(directoryPath, label, parentRealPath) {
  let stat;
  try {
    stat = await lstat(directoryPath);
  } catch (error) {
    throw new Error(`${directoryPath}: ${label} is missing or unreadable (${error.message})`);
  }
  if (stat.isSymbolicLink()) {
    throw new Error(`${directoryPath}: ${label} must not be a symbolic link`);
  }
  if (!stat.isDirectory()) {
    throw new Error(`${directoryPath}: ${label} must be a directory`);
  }
  const realPath = await realpath(directoryPath);
  if (parentRealPath && !pathIsInside(parentRealPath, realPath)) {
    throw new Error(`${directoryPath}: ${label} resolves outside the repository root`);
  }
  return realPath;
}

async function inspectRegularFile(filePath, label, approvedRealPath) {
  let stat;
  try {
    stat = await lstat(filePath);
  } catch (error) {
    throw new Error(`${filePath}: ${label} is missing or unreadable (${error.message})`, {
      cause: error,
    });
  }
  if (stat.isSymbolicLink()) {
    throw new Error(`${filePath}: ${label} must not be a symbolic link`);
  }
  if (!stat.isFile()) {
    throw new Error(`${filePath}: ${label} must be a regular file`);
  }
  const realPath = await realpath(filePath);
  if (!pathIsInside(approvedRealPath, realPath)) {
    throw new Error(`${filePath}: ${label} resolves outside its approved root`);
  }
  return realPath;
}

async function readValidatedFile(filePath, label, approvedRealPath, openFile, encoding) {
  await inspectRegularFile(filePath, label, approvedRealPath);
  let handle;
  try {
    handle = await openFile(filePath, constants.O_RDONLY | constants.O_NOFOLLOW);
  } catch (error) {
    throw new Error(`${filePath}: ${label} changed before it could be opened safely`, {
      cause: error,
    });
  }
  try {
    if (!(await handle.stat()).isFile()) {
      throw new Error(`${filePath}: opened ${label} must be a regular file`);
    }
    return await handle.readFile(encoding);
  } finally {
    await handle.close();
  }
}

async function readJsonFile(filePath, label, approvedRealPath, openFile) {
  const source = await readValidatedFile(filePath, label, approvedRealPath, openFile, "utf8");
  try {
    return JSON.parse(source);
  } catch (error) {
    throw new Error(`${filePath}: ${label} is not valid JSON (${error.message})`);
  }
}

function duplicate(values, key) {
  const seen = new Set();
  for (const value of values) {
    const identity = value[key];
    if (seen.has(identity)) return identity;
    seen.add(identity);
  }
  return null;
}

function assertRawTierIds(value, sourcePath) {
  if (!Array.isArray(value?.tiers)) return;
  if (!value.tiers.every((tier) =>
    tier !== null
    && typeof tier === "object"
    && !Array.isArray(tier)
    && typeof tier.id === "string")) return;
  const duplicateId = duplicate(value.tiers, "id");
  if (duplicateId !== null) {
    throw new Error(`${sourcePath}: duplicate tier id ${duplicateId}`);
  }
}

async function discoverCategories(categoryRoot, categoryRealPath, openFile) {
  const entries = (await readdir(categoryRoot, { withFileTypes: true }))
    .sort((left, right) => compareCodeUnits(left.name, right.name));
  const packages = [];
  for (const entry of entries) {
    const sourcePath = path.join(categoryRoot, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`${sourcePath}: category file must not be a symbolic link`);
    }
    if (!entry.isFile() || path.extname(entry.name) !== ".json") {
      throw new Error(`${sourcePath}: unexpected category entry; expected a regular .json file`);
    }
    const value = await readJsonFile(sourcePath, "category file", categoryRealPath, openFile);
    assertRawTierIds(value, sourcePath);
    packages.push({
      filenameId: path.basename(entry.name, ".json"),
      manifest: parseWordGameManifest(value, sourcePath),
      sourcePath,
    });
  }
  return packages;
}

function assertUniqueCategories(packages) {
  const ids = new Map();
  const orders = new Map();
  for (const currentPackage of packages) {
    for (const [label, value, seen] of [
      ["category id", currentPackage.manifest.id, ids],
      ["category order", currentPackage.manifest.order, orders],
    ]) {
      if (seen.has(value)) {
        throw new Error(
          `${currentPackage.sourcePath}: duplicate ${label} ${value}; first declared by ${seen.get(value)}`,
        );
      }
      seen.set(value, currentPackage.sourcePath);
    }
  }
  for (const currentPackage of packages) {
    if (currentPackage.filenameId !== currentPackage.manifest.id) {
      throw new Error(
        `${currentPackage.sourcePath}: category filename ${currentPackage.filenameId} must match category id ${currentPackage.manifest.id}`,
      );
    }
  }
}

function assertUniqueIds(values, label, sourcePath) {
  const duplicateId = duplicate(values, "id");
  if (duplicateId !== null) {
    throw new Error(`${sourcePath}: duplicate ${label} id ${duplicateId}`);
  }
}

function registerAudio(audioById, audio, sourcePath) {
  const priorText = audioById.get(audio.id);
  if (priorText !== undefined) {
    if (priorText !== audio.text) {
      throw new Error(`${sourcePath}: audio id ${audio.id} is reused with different text`);
    }
    return;
  }
  audioById.set(audio.id, audio.text);
}

function validateCategoryReferences(currentPackage, assetById, audioById, usedAssetIds) {
  const { manifest, sourcePath } = currentPackage;
  assertUniqueIds(manifest.items, "item", sourcePath);
  assertUniqueIds(manifest.tiers, "tier", sourcePath);
  const itemById = new Map(manifest.items.map((item) => [item.id, item]));
  if (!itemById.has(manifest.coverItemId)) {
    throw new Error(`${sourcePath}: coverItemId ${manifest.coverItemId} does not reference an item`);
  }

  const quizzes = manifest.tiers.flatMap(({ quizzes: tierQuizzes }) => tierQuizzes);
  assertUniqueIds(quizzes, "quiz", sourcePath);
  const targetedItems = new Set();
  for (const tier of manifest.tiers) {
    const authoredOrders = tier.quizzes.map((quiz) =>
      quiz.questions.map(({ targetId }) => targetId));
    const baselineTargets = [...authoredOrders[0]].sort(compareCodeUnits);
    if (authoredOrders.some((order) =>
      order.length !== baselineTargets.length
      || order.toSorted(compareCodeUnits).some((targetId, index) => targetId !== baselineTargets[index]))) {
      throw new Error(`${sourcePath}: tier ${tier.id} quizzes must use the same target membership`);
    }
    if (new Set(authoredOrders.map((order) => order.join("\0"))).size !== authoredOrders.length) {
      throw new Error(`${sourcePath}: tier ${tier.id} quiz orders must be different`);
    }
    if (new Set(authoredOrders.map(([firstTargetId]) => firstTargetId)).size !== authoredOrders.length) {
      throw new Error(`${sourcePath}: tier ${tier.id} first targets must be different`);
    }
  }

  for (const quiz of quizzes) {
    assertUniqueIds(quiz.questions, "question", sourcePath);
    const quizTargets = new Set();
    for (const question of quiz.questions) {
      const target = itemById.get(question.targetId);
      if (!target) {
        throw new Error(`${sourcePath}: question ${question.id} target ${question.targetId} is missing`);
      }
      if (quizTargets.has(question.targetId)) {
        throw new Error(`${sourcePath}: quiz ${quiz.id} target ${question.targetId} must appear once`);
      }
      quizTargets.add(question.targetId);
      targetedItems.add(question.targetId);
      for (const choiceId of question.choiceIds) {
        if (!itemById.has(choiceId)) {
          throw new Error(`${sourcePath}: question ${question.id} choice ${choiceId} is missing`);
        }
      }
    }
  }

  for (const item of manifest.items) {
    if (!targetedItems.has(item.id)) {
      throw new Error(`${sourcePath}: unused item ${item.id}; item is never targeted`);
    }
    registerAudio(audioById, item.labelAudio, sourcePath);
    registerAudio(audioById, item.promptAudio, sourcePath);
    if (item.visual.kind === "illustration") {
      if (!assetById.has(item.visual.assetId)) {
        throw new Error(`${sourcePath}: illustration asset ${item.visual.assetId} is not listed`);
      }
      usedAssetIds.add(item.visual.assetId);
    }
  }
}

function validateAssetRecords(assetManifest, assetManifestPath) {
  assertUniqueIds(assetManifest.assets, "illustration asset", assetManifestPath);
  const publicPaths = new Set();
  for (const asset of assetManifest.assets) {
    const filename = `${asset.id}.webp`;
    const expectedPublicPath = `/assets/word-games/illustrated/${filename}`;
    if (asset.publicPath !== expectedPublicPath) {
      throw new Error(
        `${assetManifestPath}: asset ${asset.id} publicPath must stay within the approved illustration root as ${expectedPublicPath}`,
      );
    }
    if (publicPaths.has(asset.publicPath)) {
      throw new Error(`${assetManifestPath}: duplicate illustration publicPath ${asset.publicPath}`);
    }
    publicPaths.add(asset.publicPath);
  }
  return new Map(assetManifest.assets.map((asset) => [asset.id, asset]));
}

async function validateIllustrationFiles({
  assetManifest,
  illustrationRoot,
  illustrationRealPath,
  openFile,
}) {
  const listedFilenames = new Set(assetManifest.assets.map(({ id }) => `${id}.webp`));
  const entries = (await readdir(illustrationRoot, { withFileTypes: true }))
    .sort((left, right) => compareCodeUnits(left.name, right.name));
  for (const entry of entries) {
    const filePath = path.join(illustrationRoot, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`${filePath}: illustration WebP must not be a symbolic link`);
    }
    if (listedFilenames.has(entry.name) && !entry.isFile()) {
      throw new Error(`${filePath}: illustration WebP must be a regular file`);
    }
    if (!entry.isFile() || !listedFilenames.has(entry.name)) {
      throw new Error(`${filePath}: unexpected illustration file ${entry.name}`);
    }
  }
  for (const asset of assetManifest.assets) {
    const filePath = path.join(illustrationRoot, `${asset.id}.webp`);
    const webp = await readValidatedFile(
      filePath,
      "illustration WebP",
      illustrationRealPath,
      openFile,
    );
    let metadata;
    try {
      metadata = await sharp(webp).metadata();
    } catch {
      throw new Error(`${filePath}: illustration WebP is invalid`);
    }
    if (metadata.format !== "webp" || metadata.width !== 512 || metadata.height !== 512) {
      throw new Error(`${filePath}: illustration WebP must be 512×512`);
    }
    const actualHash = createHash("sha256").update(webp).digest("hex");
    if (actualHash !== asset.sha256) {
      throw new Error(`${filePath}: WebP SHA-256 mismatch for illustration asset ${asset.id}`);
    }
  }
}

function compileAudio(audio) {
  return { ...audio, source: `/assets/audio/${audio.id}.mp3` };
}

function compileCategory(manifest, assetById) {
  return {
    ...manifest,
    items: manifest.items.map((item) => ({
      ...item,
      labelAudio: compileAudio(item.labelAudio),
      promptAudio: compileAudio(item.promptAudio),
      visual: item.visual.kind === "swatch"
        ? { ...item.visual }
        : {
            kind: "image",
            src: assetById.get(item.visual.assetId).publicPath,
          },
    })),
  };
}

function plannerLine(id, text) {
  return {
    id,
    lang: "en-US",
    speaker: "narrator",
    src: `/assets/audio/${id}.mp3`,
    text,
    ttsText: `[bright, playful teaching delivery for a young child] ${text}`,
    voiceStyle: "energetic-character",
  };
}

async function inspectAudio(audioRoot, audioRealPath, audioById, rootDir, allowMissingAudio) {
  const missingFiles = [];
  for (const id of [...audioById.keys()].sort(compareCodeUnits)) {
    const filePath = path.join(audioRoot, `${id}.mp3`);
    try {
      await inspectRegularFile(filePath, "audio file", audioRealPath);
    } catch (error) {
      if (allowMissingAudio && error.cause?.code === "ENOENT") {
        missingFiles.push(portableRelativePath(rootDir, filePath));
        continue;
      }
      throw error;
    }
  }
  return missingFiles.sort(compareCodeUnits);
}

async function compile({
  rootDir,
  categoryRoot = path.join(rootDir, "content", "word-games", "categories"),
  assetManifestPath = path.join(rootDir, "content", "word-games", "illustrated-assets.json"),
  playerManifestPath = path.join(rootDir, "content", "word-games", "player.json"),
  publicRoot = path.join(rootDir, "public"),
  audioRoot = path.join(publicRoot, "assets", "audio"),
  openFile = open,
}, allowMissingAudio) {
  const rootRealPath = await inspectDirectory(rootDir, "repository root");
  const categoryRealPath = await inspectDirectory(categoryRoot, "category root", rootRealPath);
  const publicRealPath = await inspectDirectory(publicRoot, "public root", rootRealPath);
  const audioRealPath = await inspectDirectory(audioRoot, "audio root", publicRealPath);
  if (!pathIsInside(rootRealPath, audioRealPath)) {
    throw new Error(`${audioRoot}: audio root resolves outside the repository root`);
  }
  if (!pathIsInside(path.resolve(rootDir), path.resolve(assetManifestPath))) {
    throw new Error(`${assetManifestPath}: asset manifest path is outside the repository root`);
  }
  if (!pathIsInside(path.resolve(rootDir), path.resolve(playerManifestPath))) {
    throw new Error(`${playerManifestPath}: player manifest path is outside the repository root`);
  }
  const illustrationRoot = path.join(publicRoot, "assets", "word-games", "illustrated");
  const illustrationRealPath = await inspectDirectory(
    illustrationRoot,
    "illustration root",
    publicRealPath,
  );

  const assetManifestValue = await readJsonFile(
    assetManifestPath,
    "illustration asset manifest",
    rootRealPath,
    openFile,
  );
  const assetManifest = parseIllustrationAssetManifest(assetManifestValue, assetManifestPath);
  const assetById = validateAssetRecords(assetManifest, assetManifestPath);
  await validateIllustrationFiles({
    assetManifest,
    illustrationRoot,
    illustrationRealPath,
    openFile,
  });

  const packages = await discoverCategories(categoryRoot, categoryRealPath, openFile);
  assertUniqueCategories(packages);
  const playerManifestValue = await readJsonFile(
    playerManifestPath,
    "player manifest",
    rootRealPath,
    openFile,
  );
  const playerManifest = parseWordGamePlayerManifest(playerManifestValue, playerManifestPath);
  const audioById = new Map();
  const usedAssetIds = new Set();
  for (const currentPackage of packages) {
    validateCategoryReferences(currentPackage, assetById, audioById, usedAssetIds);
  }
  for (const cue of [
    playerManifest.successAudio,
    playerManifest.retryAudio,
    playerManifest.completeAudio,
  ]) registerAudio(audioById, cue, playerManifestPath);
  for (const asset of assetManifest.assets) {
    if (!usedAssetIds.has(asset.id)) {
      throw new Error(`${assetManifestPath}: unused illustration asset ${asset.id}`);
    }
  }

  const missingFiles = await inspectAudio(
    audioRoot,
    audioRealPath,
    audioById,
    rootDir,
    allowMissingAudio,
  );
  packages.sort(
    (left, right) => left.manifest.order - right.manifest.order
      || compareCodeUnits(left.manifest.id, right.manifest.id),
  );
  return {
    compiled: {
      categories: packages.map(({ manifest }) => compileCategory(manifest, assetById)),
      player: {
        ...playerManifest,
        successAudio: compileAudio(playerManifest.successAudio),
        retryAudio: compileAudio(playerManifest.retryAudio),
        completeAudio: compileAudio(playerManifest.completeAudio),
      },
    },
    lines: [...audioById.entries()]
      .map(([id, text]) => plannerLine(id, text))
      .sort((left, right) => compareCodeUnits(left.id, right.id)),
    missingFiles,
  };
}

/** Compile every word-game package into deterministic JSON-compatible literals. */
export async function compileWordGamePackages(paths) {
  return (await compile(paths, false)).compiled;
}

/** Validate authored content while inventorying missing saved item cues. */
export async function planWordGameAudio({ rootDir }) {
  const { lines, missingFiles } = await compile({ rootDir }, true);
  return { lines, missingFiles };
}

export function serializeGeneratedWordGameCatalog(compiled) {
  if (!compiled || !Array.isArray(compiled.categories) || !compiled.player) {
    throw new TypeError("The compiled word-game catalog must contain categories and player cues.");
  }
  return `${GENERATED_WARNING}export const GENERATED_WORD_GAME_CATALOG = ${
    JSON.stringify(compiled, null, 2)
  } as const;\n`;
}
